FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN  npm install --production
RUN npm install -g next

COPY . /app

RUN npm run build

EXPOSE 3002
ENV PORT 3002

CMD next build && npm start
