FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install -g next
# RUN npm i @next/swc-linux-arm64-gnu && npm i @next/swc-linux-arm64-musl
RUN npm install

RUN npm list --depth=0

COPY . .

RUN npm audit fix --force
# RUN npm run build
# RUN next build

EXPOSE 3000
ENV PORT 3000

ARG API_KEY
ENV API_KEY=$API_KEY

# Adds the image name and tag
LABEL maintainer="Alex Jenkins <alexljenkins89@gmail.com>"
LABEL description="Data Scientist who loves building things."
LABEL org.opencontainers.image.title="convinced_frontend"
LABEL org.opencontainers.image.version="1.0.0"

# CMD next start
CMD npm run build && sleep 10s && npm run start
