version: '3'
services:
  convinced_backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
  convinced_frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3002:3002
