version: '3'
services:
  convinced_backend:
    build: ./backend
    volumes:
      - .:/app
    ports:
      - 6891:6891
  convinced_frontend:
    build: ./frontend
    volumes:
      - .:/app
    ports:
      - 3002:3002
