build:
  frontend:
    context: ./frontend
    dockerfile: Dockerfile
  backend:
    context: ./backend
    dockerfile: Dockerfile

environments:
  - backend/.env
  - frontend/.env

services:
  - name: convinced_backend
    image:
      build:
        context: ./backend
        dockerfile: Dockerfile
      env:
        - ENV_FILE=backend/.env
    ports:
      - 8000:8000

  - name: convinced_frontend
    image:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      env:
        - ENV_FILE=frontend/.env
    ports:
      - 3000:3000
