# app/Dockerfile
FROM python:3.9.13

RUN apt-get update && \
    apt-get install -y git

WORKDIR /app

ARG convinced_env

ENV convinced_env=${convinced_env} \
    PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    POETRY_VERSION=1.4.2

RUN pip3 install "poetry==$POETRY_VERSION"

# poetry
COPY poetry.lock pyproject.toml /app/
RUN poetry config virtualenvs.create false \
    && poetry install $("$convinced_env" == production && echo "--no-dev") --no-interaction --no-ansi

# Creating folders, and files for a project:
COPY . /app

EXPOSE 6891
ENV PORT 6891

ENTRYPOINT ["uvicorn", "src.api.api:app", "--reload"]
