# app/Dockerfile
FROM python:3.9.13

RUN apt-get update && \
    apt-get install -y git

WORKDIR /app

ARG API_KEY
ARG AI_KEY
ENV API_KEY=$API_KEY
ENV AI_KEY=$AI_KEY

ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    POETRY_VERSION=1.4.2

RUN pip install "poetry==$POETRY_VERSION"

COPY pyproject.toml poetry.lock /app/
COPY src /app/src

RUN poetry config virtualenvs.create false \
    && poetry install --only main --no-interaction --no-ansi

EXPOSE 6891
ENV PORT 6891

# ENTRYPOINT ["bash", "-c", "ls -R $PWD"] # confirmed only backend stuff exists here
# ENTRYPOINT ["uvicorn", "app.src.app:app", "--reload"]
ENTRYPOINT ["python", "/app/src/app.py"]
